name: search_store_app
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  http: ^0.13.4
  dartz: ^0.10.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
